### ISSUE TITLE
Consuming dictionaries from a package in node_modules

### ISSUE THREAD

**Issue by BjornHMS** [aymericzip/intlayer#317]
I'm working on an inhouse component library that uses intlayers for locales.
In the build process, I move *.content. files into dist/dictionaries and try to consume them with intlayers in another project.
I am however unable to read any of my dictionaries from the package.

Intlayers has some settings such as contentDir, exludePath and traversePattern, which are ignoring node_modules by default.
But any way I tried to configure those, I was still left without a built dictionary.
So I tried copying the package folder into the root from node_modules during some sanity testing. It still didn't work.

After more trial and error I figured out that it being in a folder called 'dist' was blocking intlayer from scanning it.
And after some brute force removal of all mention of it in the intlayer package. I finally sussed it out, a chokidar listDictionaries function has node_modules and dist .. and some others hardcoded as ignored.

Could you add a way to override those in the intlayer config?

please and thank you 😸

**Comment by aymericzip** [comment]
You're right, we have no clear doc regarding that. If you wanna submit one, I will merge it with pleasure

 We have a similar case with intlayer and our design system 

See how we reference the design system on the website : https://github.com/aymericzip/intlayer/blob/main/apps/website/intlayer.config.ts

```ts
import { dirname } from 'node:path';
import type { IntlayerConfig } from 'intlayer';

const config: IntlayerConfig = {
  content: {
    contentDir: ['./src', '../../packages/@intlayer/design-system/src'],
  }
}
```

But we do not export the .content in the package `/dist`, we point to them directly using relative path in the monorepo 

if you're exporting your .content in the `/dist`, I just pushed a new version `7.0.3-canary.0`, that will allows to refer your content as :

```ts
import { dirname } from 'node:path';
import type { IntlayerConfig } from 'intlayer';

const config: IntlayerConfig = {
  content: {
    contentDir: ['./src', require.resolve('@intlayer/design-system'),],
  }
}
```

> Note: It will works only if you package export the component as CJS

If there is not CJS export, I recommend you to add that in your design-system package.json

```json
  "exports": {
    "./package.json": "./package.json"
  },
```
 
To be able to retrieve the path as :

```ts
import { dirname } from 'node:path';
import type { IntlayerConfig } from 'intlayer';

const config: IntlayerConfig = {
  content: {
    contentDir: ['./src', dirname(require.resolve('@intlayer/design-system/package.json')),],
  }
}
```

Let me know if it helps. If not, you can use relative path

**Comment by BjornHMS** [comment]
Just some information.
The component library lives in another repo and is installed, so in the consuming project it lives under `node_modules/@pgk/` .. and so the dictionaries live in `node_modules/@pgk/dist/dictionaries`

I saw in the built configuration.json file that when I used absolute paths in contentDir the built contentDir would be mangled since the baseDir path was being prepended already.
So I was using relative paths before, and that worked..  but only if I use patch-package to alter `@intlayers/chokidar/dist/cjs/listDictionariesPath.cjs` 

I just tried the `canery` build .. now i see that absolute paths work. However .. my workaround with patch-package has broken. For some reason removing `"**/node_modules/**"` and `"**/dist/**"` from the `listDictionariesPath` ignore array no longer works.

So it's one step forwards, two steps back as far as my problems are concerned 😅

**Comment by aymericzip** [comment]
> For some reason removing "**/node_modules/**" and "**/dist/**" from the ignore array no longer works.

I have no issue removing them on my end

What would be your expected behavior ?

```ts
  content: {
    contentDir: ['./src', '../../packages/@intlayer/design-system/src'],
    excludedPath: [], // remove all excluded path 
  },
```
```ts
  content: {
    contentDir: ['./src', '../../packages/@intlayer/design-system/src'],
    excludedPath: ['**/dist/**'],  // exclude only dist  
  },
```

**Comment by BjornHMS** [comment]
You should be able to reproduce it by temporarily housing the design-system in a folder called node_modules or dist, and setting `contentDir: ['./src', '../../packages/@intlayer/dist/design-system/src'],`

setting excludePath to [] did not fix it for me, on either versions.

Like I mentioned earlier, the problem for me was `@intlayers/chokidar/dist/cjs/listDictionariesPath.cjs` excluding both the `node_modules` and `dist` folders before excludePath even has a chance to effect it.

**Comment by aymericzip** [comment]
oh you're right, good catch 

Pushed a [fix](https://github.com/aymericzip/intlayer/commit/ae9cbabae578c08430f19d2bde642d965cf05787), you can try  the `v7.0.3-canary.1` 
I hope it will help

**Comment by BjornHMS** [comment]
Beautiful, it works! thanks for the swift fix 👍
